version: '3.3'
services:
    angular:
        container_name: w2m-test
        build: 
            context: ./
            dockerfile: Dockerfile    
        restart: always
        ports:
            - '4200:80'